# Use a supported base image
FROM ubuntu:20.04

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    libprotobuf-c1 \
    && rm -rf /var/lib/apt/lists/*

# Create a directory for your application
WORKDIR /app

# Copy your binary and any dependencies
COPY ./binary /app/binary
COPY ./binary.manifest /app/binary.manifest

# the binary is executable
RUN chmod +x /app/binary